---
require:
  - rubocop-rspec
AllCops:
  Exclude:
  - 'test_app/**/*'
  - 'tmp/**/*'
  - vendor/**/*
  DisplayCopNames: true
  TargetRubyVersion: 2.3
Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
Layout/ExtraSpacing:
  AllowForAlignment: true
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/IndentHash:
  EnforcedStyle: consistent
Layout/MultilineArrayBraceLayout:
  Enabled: true
Layout/MultilineAssignmentLayout:
  EnforcedStyle: new_line
  Enabled: true
Layout/MultilineHashBraceLayout:
  Enabled: true
Layout/MultilineMethodCallBraceLayout:
  Enabled: true
Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Lint/AmbiguousBlockAssociation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Next:
  EnforcedStyle: always
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%I': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': ()
    '%w': '[]'
    '%W': '[]'
    '%x': ()
Style/TrivialAccessors:
  ExactNameMatch: false
Style/SymbolArray:
  Enabled: true
Style/BarePercentLiterals:
  EnforcedStyle: percent_q
Style/CollectionMethods:
  Enabled: true
Style/Send:
  Enabled: true
Style/AutoResourceCleanup:
  Enabled: true
Style/OptionHash:
  Enabled: true
Style/StringMethods:
  Enabled: true
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/SingleLineBlockParams:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded

# TODO is inlined so that it takes precedence.

Lint/BooleanSymbol:
  Enabled: false

Lint/InterpolationCheck:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

# Offense count: 10
Metrics/AbcSize:
  Max: 20

# Offense count: 84
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: always, conditionals
Style/AndOr:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

# Offense count: 150
# Cop supports --auto-correct.
Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_braces
Layout/IndentHash:
  EnforcedStyle: special_inside_parentheses

# Offense count: 21
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: call, braces
Style/LambdaCall:
  Enabled: false

# Offense count: 12
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
# SupportedStyles: skip_modifier_ifs, always
Style/Next:
  Enabled: false

Style/StderrPuts:
  Enabled: false

# RSpec Cops
RSpec/MessageExpectation:
  Enabled: true
RSpec/ExampleLength:
  Enabled: false
RSpec/VerifiedDoubles:
  IgnoreSymbolicNames: true
RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/mutest/**/*'


# Inlining RSpec todos for the same reason as the RSpec ones

# This configuration was generated by
# `rubocop --auto-gen-config`
# on 2017-01-27 19:41:43 -0800 using RuboCop version 0.47.1.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

RSpec/ContextWording:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

# Offense count: 89
# Configuration parameters: CustomIncludeMethods.
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/unit/mutest/meta/example/dsl_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer/config_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer/env_progress_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer/env_result_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer/mutation_progress_result_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer/mutation_result_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer/status_progressive_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer/status_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer/subject_progress_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer/subject_result_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer/test_result_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer_spec.rb'
    - 'spec/unit/mutest/reporter/cli_spec.rb'

# Offense count: 13
# Configuration parameters: CustomTransform, IgnoreMethods.
RSpec/FilePath:
  Exclude:
    - 'spec/unit/mutest/loader_spec.rb'
    - 'spec/unit/mutest/matcher/chain_spec.rb'
    - 'spec/unit/mutest/matcher/compiler/subject_prefix_spec.rb'
    - 'spec/unit/mutest/matcher/compiler_spec.rb'
    - 'spec/unit/mutest/matcher/filter_spec.rb'
    - 'spec/unit/mutest/matcher/method/instance_spec.rb'
    - 'spec/unit/mutest/matcher/method/singleton_spec.rb'
    - 'spec/unit/mutest/matcher/methods/instance_spec.rb'
    - 'spec/unit/mutest/matcher/methods/singleton_spec.rb'
    - 'spec/unit/mutest/matcher/namespace_spec.rb'
    - 'spec/unit/mutest/matcher/null_spec.rb'
    - 'spec/unit/mutest/matcher/scope_spec.rb'
    - 'spec/unit/mutest/matcher/static_spec.rb'

RSpec/ImplicitSubject:
  Enabled: false

# Offense count: 5
# Configuration parameters: AssignmentOnly.
RSpec/InstanceVariable:
  Exclude:
    - 'spec/unit/mutest/parallel/master_spec.rb'

RSpec/IteratedExpectation:
  Enabled: false

RSpec/LetBeforeExamples:
  Enabled: false

# Offense count: 93
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: allow, expect
RSpec/MessageExpectation:
  Enabled: false

# Offense count: 94
# Configuration parameters: SupportedStyles.
# SupportedStyles: have_received, receive
RSpec/MessageSpies:
  EnforcedStyle: receive

# Offense count: 5
RSpec/MultipleExpectations:
  Max: 3

# Offense count: 57
RSpec/NamedSubject:
  Enabled: false

# Offense count: 70
# Configuration parameters: Max.
RSpec/NestedGroups:
  Exclude:
    - 'spec/unit/mutest/ast/named_children_spec.rb'
    - 'spec/unit/mutest/cli_spec.rb'
    - 'spec/unit/mutest/expression/namespace/recursive_spec.rb'
    - 'spec/unit/mutest/mutation_spec.rb'
    - 'spec/unit/mutest/parallel/master_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer/mutation_result_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer/status_progressive_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer/status_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer_spec.rb'
    - 'spec/unit/mutest/reporter/cli_spec.rb'
    - 'spec/unit/mutest/repository/diff_spec.rb'
    - 'spec/unit/mutest/runner/sink_spec.rb'

RSpec/ScatteredLet:
  Enabled: false

RSpec/VoidExpect:
  Enabled: false

# Offense count: 18
# Configuration parameters: IgnoreSymbolicNames.
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/unit/mutest/actor/binding_spec.rb'
    - 'spec/unit/mutest/integration/rspec_spec.rb'
    - 'spec/unit/mutest/reporter/cli/printer_spec.rb'
    - 'spec/unit/mutest/repository/subject_filter_spec.rb'
    - 'spec/unit/mutest/result/mutation_spec.rb'
    - 'spec/unit/mutest/subject/method/instance/memoized_spec.rb'
    - 'spec/unit/mutest/subject_spec.rb'
