steps:
  - command: "build/run 2.3.3 'rspec spec/unit'"
    label: ":rspec: RSpec"
    agents:
      - queue=elastic
    env:
      COVERAGE: 'true'

  - name: ':rspec: Corpus tests (rubyspec)'
    command: build/run 2.3.3 'rspec --tag corpus:rubyspec'
    agents:
      - queue=elastic

  - name: ':rspec: Corpus tests (regexp_parser)'
    command: build/run 2.3.3 'rspec --tag corpus:regexp_parser'
    agents:
      - queue=elastic

  - name: ':rspec: Corpus tests (axiom)'
    command: build/run 2.3.3 'rspec --tag corpus:axiom'
    agents:
      - queue=elastic

  - name: ':rspec: Integration tests'
    command: build/run 2.3.3 'rspec --exclude-pattern "**/corpus_spec.rb" --format documentation spec/integration'
    agents:
      - queue=elastic

  - name: ':skull: Mutest'
    command: build/run 2.3.3 'rake metrics:mutest'
    timeout_in_minutes: 10
    agents:
      - queue=elastic

  - name: ':rubocop: Rubocop'
    command: build/run 2.3.3 'rubocop --config config/rubocop.yml'
    agents:
      - queue=elastic
