---
Attribute:
  enabled: false
  exclude: []
BooleanParameter:
  enabled: true
  exclude: []
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
  exclude:
  - Mutest::Expression#match_length
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: false
  exclude: []
  max_calls: 1
  allow_calls: []
FeatureEnvy:
  enabled: false
# Buggy smell detector
IrresponsibleModule:
  enabled: false
  exclude: []
LongParameterList:
  enabled: true
  exclude:
  - Mutest::Matcher::Method::Instance#self.build
  - Mutest::Meta::Example::DSL # 3 vars
  max_params: 2
LongYieldList:
  enabled: true
  exclude: []
  max_params: 2
NestedIterators:
  enabled: true
  exclude:
  - Mutest#self.singleton_subclass_instance
  - Mutest::CLI#parse
  - Mutest::Mutator::Node::Arguments#emit_argument_mutations
  - Mutest::Mutator::Node::Resbody#mutate_captures
  - Mutest::Mutator::Util::Array::Element#dispatch
  - Mutest::Parallel::Master#run
  - Mutest::RequireHighjack#self.call
  - Mutest::Selector::Expression#call
  - Parser::Lexer#self.new
  max_allowed_nesting: 1
  ignore_iterators: []
NilCheck:
  enabled: false
RepeatedConditional:
  enabled: true
  exclude:
  - Mutest::Mutator
  - Mutest::Meta::Example::DSL
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  exclude:
  - Mutest::Mutator # 4 vars
  - Mutest::Parallel::Master # 4 vars
  - Mutest::Meta::Example::DSL # 4 vars
  max_instance_variables: 3
TooManyMethods:
  enabled: true
  exclude:
  - Mutest::CLI
  - Mutest::Mutator::Node
  - Mutest::Parallel::Master
  max_methods: 10
TooManyStatements:
  enabled: true
  exclude:
  - Mutest::CLI#add_debug_options
  - Mutest::CLI#add_environment_options
  - Mutest::Reporter::CLI::Printer::Config#run
  - Mutest::Reporter::CLI::Printer::EnvProgress#run
  - Mutest::Runner#run_driver
  - Mutest::Zombifier::File#self.find
  max_statements: 7
UncommunicativeMethodName:
  enabled: true
  exclude:
  - Mutest::AST::Sexp#s
  - Mutest::Mutation#sha1
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: ['force_utf32']
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  exclude:
  - Mutest::AST::Sexp#s
  - Mutest::Actor::Env#new_mailbox
  - Mutest::CLI#reporter
  - Mutest::Integration::Null#call
  - Mutest::Integration::Rspec#parse_example
  - Mutest::Integration::Rspec#parse_expression # intentional, private
  - Mutest::Meta::Example::Verification#format_mutations # intentional, private
  - Mutest::Reporter::CLI::Format::Progressive#new_buffer
  - Mutest::Reporter::CLI::Printer::StatusProgressive#object # False positive calls super
  - Mutest::Repository::Diff#tracks? # intentional, private
  - Mutest::Repository::Diff#within_working_directory? # intentional, private
  max_helper_calls: 0
